apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: kserve-lgbserver
spec:
  supportedModelTypes:
    - name: lightgbm
      version: "0"
  containers:
    - name: kserve-container
      image: kserve-lgbserver:replace
      args:
        - --model_name={{.Name}}
        - --model_dir=/mnt/models
        - --http_port=8080
        - --nthread=1
